apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  # Konfigurasi Listeners Internal dan Advertised
  KAFKA_BROKER_ID: "1"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT

  # PENTING: Menggunakan IP/Hostname '0.0.0.0'
  KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
  
  # PENTING: Menggunakan nama Service Kubernetes 'kafka'
  KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092 
  
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  
  # Konfigurasi Kraft (Controller dan Broker)
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_NODE_ID: "1"
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093

  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk # CLUSTER_ID ini harus tetap konstan