server:
    port: 9000
    
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
                server:
                    webmvc:
                        routes:
                            - id: product
                              uri: lb://product-service
                              predicates: 
                                - Path=api/products/**
                            - id: customer
                              uri: lb://customer-service
                              predicates: 
                                - Path=api/customers/**
                            - id: order
                              uri: lb://order-service
                              predicates: 
                                - Path=api/orders/**

                            - id: buku
                              uri: lb://buku-service
                              predicates: 
                                - Path=api/buku/**

                            - id: peminjaman
                              uri: lb://peminjaman-service
                              predicates: 
                                - Path=api/peminjaman/**

                            - id: pengembalian
                              uri: lb://pengembalian-service
                              predicates: 
                                - Path=api/pengembalian/**

                            - id: anggota
                              uri: lb://anggota-service
                              predicates: 
                                - Path=api/anggota/**
                    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus # Izinkan prometheus masuk
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name} # Biar ketauan ini data dari servis mana