global:
  scrape_interval: 10s # Ambil data tiap 10 detik

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus' # Jalur rahasia data metrics
    static_configs:
      targets:
        - 'buku-service:8085'
        - 'anggota-service:8084'
        - 'peminjaman-service:8083'
        - 'pengembalian-service:8086'
        - 'eureka-server:8761'
        - 'API-GATEWAY:9000'