version: '3.8'

services:
  # 1. OTAKNYA (Database Log)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Penting! Batasi RAM biar laptop gak meledak
    ports:
      - "9200:9200"
    networks:
      - microservices-net

  # 2. PENGUMPUL LOG (Tukang Sortir)
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: logstash
    ports:
      - "5000:5000/tcp" # Pintu masuk log dari Spring Boot
      - "9600:9600"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline # Kita butuh config ini
    depends_on:
      - elasticsearch
    networks:
      - microservices-net

  # 3. WAJAHNYA (Dashboard)
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - microservices-net

# PENTING: Gunakan network yang SAMA dengan microservices kamu
networks:
  microservices-net:
    external: true
    name: arsitekturberbasislayanan_microservices-network