version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17 # Menggunakan versi Java 17 (sesuai Spring Boot 3)
    container_name: jenkins-server
    build: .
    user: root
    ports:
      - "9090:8080" # Akses Web UI
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      # PENTING: Mounting Docker Socket agar Jenkins bisa menjalankan perintah 'docker build'
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge